spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

logging:
  level:
    root: info
    "[org.hibernate.SQL]": debug